### ISSUE TITLE
Make collection of lower/upper bounds configurable

### ISSUE THREAD

**Issue by aokolnychyi** [apache/incubator-iceberg#173]
Storing lower/upper bounds might significantly increase the size of metadata for datasets with a big number of columns, which can degrade the performance of metadata operations. In most cases, users cluster/sort their data by a subset of data columns to have fast queries with predicates on those columns. In my view, it is reasonable to have a list of columns for which we want to collect stats and that should be configurable by the user.

Another option here is to add a flag to keep stats only for top-level columns. I believe the first approach is more flexible and will help us to properly support nested datasets. This will be really beneficial in light of upcoming changes for nested data in Spark.

This feature should coexist with #113.

**Comment by aokolnychyi** [comment]
I am wondering about the best way to implement this feature.

A few ideas that came to my mind are below.

**Option 1 (TableProperties)**

We will have to add multiple new properties.
For example, we might use something like this:

```
metrics.collection.enabled
metrics.collection.column-delimiter
metrics.collection.bounds.enabled
metrics.collection.bounds.columns
```

Instead of storing a list of columns, we can store a regular expression.

Then we will be able to construct a `MetricsSpec` based on those properties and pass it to writers.

**Option 2 (Extend Metadata)**

The previous option is a bit cumbersome. Alternatively, we can store a `MetricsSpec` directly in the metadata (similar to `PartitionSpec`) and expose an API to update it. Also, users will be able to provide a correct `MetricsSpec` while creating tables. 

@rdblue any suggestions on this?

**Comment by rdblue** [comment]
I'd prefer the simpler table property approach because it can be configured using existing SQL DDL (`SET TBLPROPERTIES`). Here's what I would do to keep the configuration small:

1. Define modes: `full`, `counts`, and `none` to express all metrics, just null/value counts, and no metrics
2. Allow setting a column default: `metadata.metrics.default=full`
3. Add column-level config: `metadata.metrics.column.(column-name)=counts` to allow per-column tuning

That way, the configuration stays simple and users can choose how to minimize the amount of configuration properties they need to set by controlling the default and then updating individual columns from there.

**Comment by aokolnychyi** [comment]
That's a clean way to control it! Let me go ahead and implement this.

**Comment by aokolnychyi** [comment]
@rdblue in light of recent changes, am I correct that this PR is about `value_counts`, `null_value_counts`, `lower_bounds`, `upper_bounds` only?

**Comment by rdblue** [comment]
@aokolnychyi, I think that sounds good.
