### ISSUE TITLE
Add mechanism to expire old metadata versions

### ISSUE THREAD

**Issue by arina-ielchiieva** [apache/incubator-iceberg#181]
Based on the discussion on dev mailing list:

Ryan Blue

> So far, we’ve kept these around to help troubleshoot format problems. It has been a fairly cheap way to be able to see exactly what happened to the table. But we’re also getting to the point where we no longer need to refer back to them and should think about adding a way to remove them. Technically, you don’t need to keep them around once you’ve committed the new version, but an easy way to roll back is to change the database pointer so it is nice to keep a few of them.
I think we can probably build a way to expire old metadata versions by looking for a naming pattern, like v(num)-(uuid).metadata.json[.gz].

**Comment by rdblue** [comment]
From discussion on #309, I think the right way to expire old metadata is to keep a list of the N previous metadata files in each metadata file, then regularly clean up the old files after each commit. Both the number of old versions and whether to delete the oldest file after each commit should be configured by a table properties.

We can also add additional checking in the snapshot expiration code since we can go back and read the old metadata locations to find what should have been deleted (but may have failed).

**Comment by rdblue** [comment]
Adding this to the 0.8.0 release milestone.

**Comment by rdblue** [comment]
Regular cleanup was added in #631, and #873 added the ability to clean orphan data files for any that were missed. I'm going to close this.
