### ISSUE TITLE
Normalize NaN values for bucketing

### ISSUE THREAD

**Issue by electrum** [apache/incubator-iceberg#295]
We should use `doubleToLongBits` rather than `doubleToRawLongBits`. This allows pushdown of expressions like `is_nan(x)` that check if a value is NaN (compared to normal equality as  NaN values are never equal).

**Comment by timmylicheng** [comment]
A quick PR https://github.com/apache/incubator-iceberg/pull/303

**Comment by electrum** [comment]
I just noticed that bucketing by float or double is not actually allowed by the specification, nor does the Iceberg library implement. However, the specification mentions how to hash these types, for seemingly no purpose. Would it be better to remove the hash specification to avoid confusion?

FWIW, I agree with the decision to not include bucketing on floating point numbers, since this will almost certainly cause problems and user confusion in practice.

**Comment by timmylicheng** [comment]
There is a short description in spec.md on this "2. Float hash values are the result of hashing the float cast to double to ensure that schema evolution does not change hash values if float types are promoted. Note that floating point types are not valid source values for partitioning."

But I agree with you. Having the comments saying bucketing by float or double is not allowed, the actual implementation seems useless.

How about I remove the description in spec.md as well as BucketFloat and BucketDouble class?

@rdblue Thoughts

**Comment by rdblue** [comment]
I forgot that I had already thought about bucketing with floating point numbers and decided it was a bad idea. I'm glad you guys caught that in the spec (and that we wrote it down!).

The reason to define a hash function for floating point numbers is that we may need it for other uses, and we need to be careful with hashing and schema evolution.

The hash spec produces the same result for a value in all types the value may later be promoted to. That's why `h(1) == h(1L)`. That is required for bucketing to work when a bucketed column is promoted from `int` to `long`. While we don't support bucketing on floating point values, I think this property should be preserved if we ever do use the hash spec with floating point values.

**Comment by timmylicheng** [comment]
@rdblue Getcha.
@electrum Shall I leave the codes there and just update the spec.md with wording like "float(double) is not supported. Be careful."?

**Comment by timmylicheng** [comment]
PR #303 is merged btw. @electrum

**Comment by electrum** [comment]
@timmylicheng thanks!

**Comment by electrum** [comment]
I'd prefer to remove it from the specification (maybe just comment it out in the specification source for easy restoration) to avoid confusion, but that's @rdblue's call.

**Comment by rdblue** [comment]
What about adding a note that points out that the hash function is defined, but bucketing by floating point values is not allowed?
