### ISSUE TITLE
Orphan manifest file when performing delete in transaction

### ISSUE THREAD

**Issue by arina-ielchiieva** [apache/incubator-iceberg#330]
Steps to reproduce:

1. Create Iceberg table and add two files:
```
    Tables tables = new HadoopTables();

    Schema schema = new Schema(
      required(1, "id", Types.IntegerType.get()),
      required(2, "date", Types.StringType.get())
    );

    PartitionSpec spec = PartitionSpec.builderFor(schema)
      .identity("id")
      .build();

    Table table = tables.create(schema, spec, "iceberg-table");

    DataFile file_a = DataFiles.builder(spec)
      .withPath("iceberg-table/data-a.parquet")
      .withFileSizeInBytes(0)
      .withPartitionPath("id=0")
      .withRecordCount(2)
      .build();

    DataFile file_b = DataFiles.builder(spec)
      .withPath("iceberg-table/data-b.parquet")
      .withFileSizeInBytes(0)
      .withPartitionPath("id=1")
      .withRecordCount(2)
      .build();

    table.newAppend()
      .appendFile(file_a)
      .commit();

    table.newAppend()
      .appendFile(file_b)
      .commit();
```
Each append operation produces snapshot and corresponding manifest files:
```
iceberg-table/metadata/0f29e64b-b181-4cd5-b812-9dd339470b72-m0.avro
iceberg-table/metadata/08740186-305d-4d95-b79a-97cce9cbeb18-m0.avro
iceberg-table/metadata/snap-1085365639864830772-1-0f29e64b-b181-4cd5-b812-9dd339470b72.avro
iceberg-table/metadata/snap-1154652068483978044-1-08740186-305d-4d95-b79a-97cce9cbeb18.avro
```
2. Delete one file in transaction:
```
    Transaction newTransaction = table.newTransaction();
    newTransaction.newDelete()
      .deleteFile(file_a)
      .commit();
    newTransaction.commitTransaction();
```
After delete operation, new snapshot is created with two manifest files:
```
iceberg-table/metadata/dc0ad7f2-1256-4449-99dd-a6d201413794-m0.avro
iceberg-table/metadata/dc0ad7f2-1256-4449-99dd-a6d201413794-m3.avro
iceberg-table/metadata/snap-3924283385560426818-2-dc0ad7f2-1256-4449-99dd-a6d201413794.avro
```
When listing manifest files from the snapshot, it shows only one manifest file:
```
    Snapshot snapshot = table.currentSnapshot();
    snapshot.manifests().stream()
      .map(ManifestFile::path)
      .forEach(System.out::println);
```
Result: 
```
iceberg-table/metadata/dc0ad7f2-1256-4449-99dd-a6d201413794-m3.avro
```

If delete operation is performed not in transaction, only one manifest file is created:
```
    table.newDelete()
      .deleteFile(file_a)
      .commit();
```
Result:
```
iceberg-table/metadata/11368504-6738-47e0-a865-1733d972d156-m1.avro
iceberg-table/metadata/snap-943059452884103391-1-11368504-6738-47e0-a865-1733d972d156.avro
```

Issue was found when orphaned manifest files were not deleted during snapshots expiration process.

**Comment by rdblue** [comment]
Here's my response from the dev list:

I suspect that this has something to do with PR #218 that introduced special handling for files that are deleted in transactions. The problem that PR fixed was that a manifest was created, merged, and then deleted. Then the transaction failed to commit and retried. The manifest that was created was reused, but in the retry it didn’t get merged and was still a valid metadata file. Since the file had been deleted on the first try, the table was missing a manifest.

The fix was to introduce a lazy delete for cleaning up. The transaction keeps track of files to delete and deletes them after the commit succeeds. What might be happening here is the first time the transaction tries to commit, it is out of date and retries, then the original manifest is not deleted on the second attempt. Looking at the cleanup code, I think this looks like the problem because the filtered manifest cache is cleared as files are deleted: https://github.com/apache/incubator-iceberg/blob/master/core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java#L336

I think the fix is to add a list of files that should be deleted on every attempt. When the filtered cache is cleared, each file should be deleted and moved to the delete list. That way future attempts also delete the files.

**Comment by rdblue** [comment]
@arina-ielchiieva, could you test whether that solution fixes the problem?

**Comment by rdblue** [comment]
Another option for the fix is to avoid clearing the `deletedFiles` object that tracks deleted files in `BaseTransaction`. Instead, that could keep track of all files that were deleted in any attempt and avoid deleting any manifest or manifest list that is in any of the transaction's snapshots. That's a bit more complicated since there are multiple snapshots being committed, but it would probably be safer and not too difficult.

**Comment by arina-ielchiieva** [comment]
@rdblue thanks for the details. Looks like you have identify root cause correctly.
When I have commented out `filteredManifests.remove(manifest);` line:
```
  private void cleanUncommittedFilters(Set<ManifestFile> committed) {
    // iterate over a copy of entries to avoid concurrent modification
    List<Map.Entry<ManifestFile, ManifestFile>> filterEntries =
        Lists.newArrayList(filteredManifests.entrySet());

    for (Map.Entry<ManifestFile, ManifestFile> entry : filterEntries) {
      // remove any new filtered manifests that aren't in the committed list
      ManifestFile manifest = entry.getKey();
      ManifestFile filtered = entry.getValue();
      if (!committed.contains(filtered)) {
        // only delete if the filtered copy was created
        if (!manifest.equals(filtered)) {
          deleteFile(filtered.path());
        }

        // remove the entry from the cache
        //filteredManifests.remove(manifest);
      }
    }
  }
```
Delete operation in transaction produced only one manifest file.
Is what need to be fixed (to tell the truth I did not completely explore the code,  just tried out the suggested fix)?

**Comment by rdblue** [comment]
Great, thanks for testing it out. I think that the second fix I suggested is probably the way to go. That's basically what the other operations already do, we would just need to union the set of committed metadata files together and delete whatever isn't in that set.

**Comment by arina-ielchiieva** [comment]
@rdblue since you know the internals of this problem better, I think its more reasonable for your to prepare the fix. Thanks for looking into this!
