### ISSUE TITLE
Spec: Add file and position delete files

### ISSUE THREAD

**Issue by rdblue** [apache/incubator-iceberg#359]
One option for encoding row-level deletes is to track rows by file and row position in the file. This format should be documented in the spec.

**Comment by chenjunjiedada** [comment]
What format do we want for the delete files? Avro?

We need to read through the filtered parquet to construct the delete files, right?

**Comment by chenjunjiedada** [comment]
Just for information and answer questions myself. I did some POC to generate delete files in Parquet format with additional meta columns. The approach is to generate dataframe according to filters and then extend the internal row with metadata. It works fine but looks a bit strange that we spawn spark tasks in a table format, which means it has some write amplification when deleting by filters. But it should be ok if the deletion records are provided by Spark like Hudi. This reminds me that we can add an API like `deleteByRowKeys(Iteratable<InternalRows>)`

**Comment by chenjunjiedada** [comment]
Just FYI, I did an early PoC based on file and position deletion files [here](https://github.com/chenjunjiedada/incubator-iceberg/tree/row-level-delete). Since the file name should be most same so I store it as parquet file for dictionary encoding.  I will submit a PR for this soon.

**Comment by rdblue** [comment]
I think the delete file format (Avro, Parquet, ORC) should be up to the implementation. I would use the table's default format. That is normally Parquet, but ORC users would probably want both data and delete files to be ORC. Similarly, Avro doesn't require additional modules, so if a table sets its format to Avro then it makes sense to also use Avro for deletes.

Looking forward to a read/writer PR for this. Thank you, @chenjunjiedada!

**Comment by chenjunjiedada** [comment]
Make sense. Thanks!

**Comment by chenjunjiedada** [comment]
Hi @rdblue , I 'd like to confirm a couple of things to continue:

1. For the write path, before we have spark [interfaces ](https://docs.google.com/document/d/1X0NsQSryvNmXBY9kcvfINeYyKC-AahZarUqg3nS1GQs/edit#)and [SortOrder](https://github.com/apache/incubator-iceberg/issues/317), my idea is to build a filtered and sorted data frame and save it to staging table, append the added files and then drop staging table metadata.  What do you think?
```java
    dataFrame.select( s"_file", s"_pos").sort(s"_file")
      .write
      .format("iceberg")
      .option(DEFAULT_FILE_FORMAT, format)
      .mode("append")
      .save(tablePath)
```

2. For the read path, my understanding is we don't want the deletion file filtering logic right now because that depends on the sequence number. So the read path here contains only the logic that extracts the deletion files from scan task and read them as Iterators for mergeInterator. Does this make sense to you?

**Comment by rdblue** [comment]
@chenjunjiedada, I'm not sure I understand.

This issue tracks updates to the spec that detail how to write file/position delete files. That boils down to things like this:

* The files must be a supported Iceberg format and are valid Iceberg data files, just like all Iceberg metadata files
* The schema of the file/position files; probably string file path and long position in a file. Maybe that should be int instead of long?
* Rows in the delete file must be sorted by position. Should we also sort by path?

We also need a reader and writer implementation for these.

**Comment by chenjunjiedada** [comment]
I put an early [PR](https://github.com/apache/incubator-iceberg/pull/885) for the spec.

It uses integer for the position, that should be enough for most cases unless we have files that larger than 8G (roughly 2^31 rows of integer). But there may exist very special cases like files with most same rows and that could be dictionary and RLE encoded.

For the sorting requirement, I prefer to sort with both path and position(I assume the records already cluster by path, so sort with path should be easy) so that the merge sort could take advantage of it.

For the reader and writer, I will create a separate PR later.

**Comment by rdblue** [comment]
I don't understand what #885 has to do with the spec. That updates `DataFile`. The spec is [this document](http://iceberg.apache.org/spec) that details the Iceberg at-rest format. Maybe you used the wrong branch?

For position, I think we should use a long after all. That's what `DataFile` uses to encode the number of rows, and I've seen Parquet files with more than 2 billion rows before.

I agree that we should sort by both path and position, but this will require support from the processing engine because the file contents could be large.

**Comment by chenjunjiedada** [comment]
Sorry for the confusion,  I just open https://github.com/apache/incubator-iceberg/pull/887. 

No matter what column it sort with, we all need a processing engine to handle it, don't we? I 'm thinking of the case of the Spark `SupportsDelete` interface, with the given filter we have to call the spark to build the dataframe for deletion file. But Iceberg may have some generic APIs such as deleting rows in file scope or partition scope in the future. That may not need the processing engine.

**Comment by rdblue** [comment]
`SupportsDelete` won't be used to create delete files because Iceberg should not call into Spark's API as you describe. Instead, Spark should attempt the metadata-level delete and fall back to a merge-based delete.

**Comment by chenjunjiedada** [comment]
Hi @rdblue , I'm working on the reader and writer for delete files. As for the reader, the input and output are clear as the delete files would be extracted from `FileScanTask` and the output would be iterable of `InternalRow` or `GenericRecord`. While for the writer, I 'm not very sure since how metadata-level delete will be implemented. For the spark engine, I could imagine two possible ways:

- spark build the table scan with the filter expression and projection of the partition columns and metadata columns then save the data frame in append mode with an option like `data=diff`. In this case, Iceberg can generate partition level delete files from the input partition. That means we may not need a separate writer, maybe some update in the current table writer.

- spark has a `DeleteScan` plan like the table scan, each task read the input file with filter(residual) and then write to delete file.  In this case, we need a separate writer that takes the input file and filter expression as input and writes the filtered records. This would need residual evaluation for every supported format, but we can use `IcebergGenerics` to handle this.

Both of them depend on spark side implementation, any thought?

**Comment by rdblue** [comment]
The object model used by these files can be swapped out just like any Avro file. If we want to pass this information to Spark, then we would use the Spark reader classes. For most internals, we build classes that implement `IndexedRecord`.

**Comment by chenjunjiedada** [comment]
@rdblue , I don't quite follow the last comment. Do you mean the object model for delete files could be Avro in-memory data model so that it could be used by other engines as well?

**Comment by rdblue** [comment]
Whatever is consuming the file can use its own object model. When Iceberg loads metadata files, we use classes that extend `IndexedRecord` so that Avro can construct them directly like a specific record. An example of this is `GenericDataFile`.

However, there are cases where the metadata files are read by engines, like the metadata tables. When you read the `entries` metadata table, Iceberg creates tasks out of the manifest Avro files and Spark reads the data as InternalRow directly.

Delete files would be similar to these cases. If the engine needs to read a delete file, it would be able to use its object model with Avro. But I think that we will need an `IndexedRecord` implementation for file/position deletes so that we can build a filter that merges that stream with a data file record stream.

**Comment by chenjunjiedada** [comment]
So for the reader side, we want to load delete files into memory as Avro in-memory model so that engines are able to convert them to their own data model. Basically we need

1. The data access mode for delete files.
```java
class DeletedRecord implements IndexedRecord, SpecificData.SchemaConstructable
```
2. Format related value readers for ```IndexedRecord```
```java
// ParuqetAvroValueReader for IndexedRecord
class IndexedRecordReader<R extends IndexedRecord> extends StructReader<Record, Record>

// OrcArvoValueReader for IndexedRecord
// ...
// AvroValueReader for IndexedRecord
// should already exists
```
3. Engine specific file readers.

Please help to correct me if my understanding isn't correct.

**Comment by chenjunjiedada** [comment]
> But I think that we will need an IndexedRecord implementation for file/position deletes so that we can build a filter that merges that stream with a data file record stream.

@rdblue , I 'm still confusing about this, could you please help me to understand why we need this? Every engine should have its data model that means it could build the filter based on its data model. For example, the spark engine could build the filter on `InternalRow` that from base file and delete file. Thanks in advance.

I also create a draft PR: https://github.com/apache/incubator-iceberg/pull/971.

**Comment by rdblue** [comment]
I'm going to close this because the spec part is done. We can track the reader in #971, or open another issue for it in the milestone.
