### ISSUE TITLE
Remove the private field of "name" from Dates and Timestamps

### ISSUE THREAD

**Issue by waterlx** [apache/incubator-iceberg#429]
The proposal is not about any logic change, but about code implementation.
In org.apache.iceberg.transforms.Dates and Timestamps, A private field called "name" is included as a String. 
It seems that it is only used in `toString()` and could be substituted by `ChronoUnit.toString()` (although there are slight differences, like "year" (current name) vs. "Years" (`ChronoUnit.YEARS.toString()`)

This change could make the code a little simpler, save some memory (by eliminating a field as String), and also be of the help when there is a need to add more constant into Dates and Timestamps enum, like SECOND... (is there any need ?)

**Comment by waterlx** [comment]
Make any sense to you ? @rdblue

**Comment by rdblue** [comment]
I understand what you intend here, but I don't think there is much value to making this change. The memory required is negligible and I think it is more explicit to use a name field instead of relying on behavior of some third-party class that is not guaranteed. Iceberg shouldn't depend on ChronoUnit's toString to write its metadata correctly.

**Comment by waterlx** [comment]
I agree @rdblue and will close this issue, thanks for sharing your idea patiently.
