### ISSUE TITLE
Consider making snapshot ids inheritable

### ISSUE THREAD

**Issue by aokolnychyi** [apache/incubator-iceberg#504]
Right now, we have to rewrite manifests to update entries' snapshot ids while appending manifests to a table. We should consider using the approach we planned for sequence numbers to make snapshot ids inheritable. That way, we won't have to rewrite manifests.

**Comment by chenjunjiedada** [comment]
Hi @aokolnychyi, 
One question about inheriting the snpahostId, If the new manifests inherit the snapshot id, does that means the time travel feature broken since one snaphost may has different dataset at different time?

**Comment by aokolnychyi** [comment]
@chenjunjiedada, sorry, I missed your comment.

I think data files should optionally inherit the snapshot id and we still want to keep a way to explicitly annotate files with snapshot ids in manifests. For example, it is safe to inherit the snapshot id while appending files but we still want to annotate different files with their respective snapshot ids while compacting manifests, for example.

**Comment by aokolnychyi** [comment]
I am actually thinking to rename this issue into something more generic. Let me see if we can have a common way to inherit some metadata.

**Comment by chenjunjiedada** [comment]
@aokolnychyi, Thanks for your explanation.

I think I didn't understand the use case you mentioned.  I thought a new manifest should always have a new snapshot ID whatever entries it takes.  While you were considering the checkpoint or compacting thing so that the manifest should contain the same snapshot as its original manifest. Do I understand correctly now?
