### ISSUE TITLE
[Bug] Timestamp based day transformed partitions fails on read

### ISSUE THREAD

**Issue by prodeezy** [apache/incubator-iceberg#505]
Changes were made in https://github.com/apache/incubator-iceberg/pull/424 to have Timestamp day() to return Date type instead of Integer ordinal. This is causing partition interpretation to fail during append/read. Here's an example ..

```

scala> import org.apache.iceberg.types.Types.NestedField._
import org.apache.iceberg.types.Types.NestedField._

scala> import org.apache.iceberg.types._
import org.apache.iceberg.types._

scala> import org.apache.iceberg._
import org.apache.iceberg._


scala> val timestampSchema = new Schema(optional(1, "timestamp", Types.TimestampType.withoutZone()))
timestampSchema: org.apache.iceberg.Schema =
table {
  1: timestamp: optional timestamp
}

scala> val partitionByDate = PartitionSpec.builderFor(timestampSchema).day("timestamp", "date").build
partitionByDate: org.apache.iceberg.PartitionSpec =
[
  date: day(1)
]

scala> DataFiles.builder(partitionByDate).withPath("/path/to/data-1.parquet").withFileSizeInBytes(0).withRecordCount(0).withPartitionPath("date=2018-06-08").build()

java.lang.UnsupportedOperationException: Unsupported type for fromPartitionString: date
  at org.apache.iceberg.types.Conversions.fromPartitionString(Conversions.java:70)
  at org.apache.iceberg.DataFiles.fillFromPath(DataFiles.java:83)
  at org.apache.iceberg.DataFiles.access$200(DataFiles.java:36)
  at org.apache.iceberg.DataFiles$Builder.withPartitionPath(DataFiles.java:292)
  ... 55 elided

```

`org.apache.iceberg.types.Conversions` class doesn't support `Date` type handling. The impact this has is when one has PartitionSpec containing day() transformed field, doing operations like append to such a Table requires re-interpreting this field. This could potentially affect other flows as well.

**Comment by prodeezy** [comment]
cc @rdblue

**Comment by prodeezy** [comment]
Gist to reproduce : https://gist.github.com/prodeezy/459422d1b7d388a0d225292a62817b19

**Comment by aokolnychyi** [comment]
@prodeezy will resolving #428 fix this?

**Comment by prodeezy** [comment]
@aokolnychyi  yes seems like it. I put up a PR with a potential fix, maybe you can review it? I'm handling it in `Conversions` by returning an epochday ordinal which is in a Integer.  https://github.com/apache/incubator-iceberg/pull/506

**Comment by rdblue** [comment]
Doesn't PR #506 fix #428? That's basically what it does.

I'm fine adding that commit if it unblocks you, but this type of bug is going to keep happening to you if you continue to use this pattern where you write files and then use paths to build partition data when appending to a table. The `withPartitionPath` method is only intended for use with Hive partitions, and even then it is a best effort. Iceberg doesn't guarantee that partition strings even can be parsed to produce the original value because that has been an error prone anti-pattern in Hive.

This is going to cause further problems with strings that require escaping, hourly partitions, etc. I suggest moving off of this pattern and keeping the partition tuples as data instead of recovering partition tuple values like this.

**Comment by prodeezy** [comment]
There's some internal code that builds `DataFile` objects and augments the commit process. We need to re-think that code a bit. Until we work around that we need this issue fixed.

**Comment by rdblue** [comment]
Sounds good to me, I just want to make sure you don't hit this again in a few weeks for a similar use case, like hourly partitions. We should be able to get the fix in today.
