### ISSUE TITLE
Cannot update an Iceberg dataset from a Parquet file due to "field should be required, but is optional"

### ISSUE THREAD

**Issue by andrei-ionescu** [apache/incubator-iceberg#510]
Given an Iceberg dataset found at `targetPath` with the following schema named `icebergSchema`:
```
table {
  1: optionalField: optional string
  2: requiredField: required string
}
```
And given an Parquet file found at `sourcePath` with the following schema:
```
message spark_schema {
  optional binary optionalField (UTF8);
  required binary requiredField (UTF8);
}
```
Please note that both have the same schema.

When I do:
```java
sparkSession
        .read().schema(SparkSchemaUtil.convert(icebergSchema)).parquet(sourcePath)
        .write().format("iceberg").mode(SaveMode.Append).save(targetPath);
```
It fails with:
```
Cannot write incompatible dataset to table with schema
table {
  1: optionalField: optional string
  2: requiredField: required string
}
Problems:
* requiredField should be required, but is optional
```

I did debug it and found that at https://github.com/apache/incubator-iceberg/blob/master/api/src/main/java/org/apache/iceberg/types/CheckCompatibility.java#L135 Iceberg checks for `nullable` compatibility for each field which is a correct logic to apply.

Now, at read time Spark loosens the nullability constraint by setting the `nullable` property of each field to `true`. This is done here: https://github.com/apache/spark/blob/branch-2.4/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/DataSource.scala#L380.

From what I've found, there are two PRs trying to solve this:

- https://github.com/apache/spark/pull/14124
- https://github.com/apache/spark/pull/17293

In the first one I found this interesting mailing archive [Re: Spark SQL: Preserving Dataframe Schema](https://www.mail-archive.com/user@spark.apache.org/msg39235.html) saying:

> As an academic aside, note that all datatypes are nullable according to the
> SQL Standard.

In the second one I found the [following comment](https://github.com/apache/spark/pull/17293#issuecomment-482328688) as a conclusion:

> Does the closure of this PR imply that setting nullable=false in a custom (user-defined) schema will never have an effect when loading CSV or JSON data from a file? In other words, if someone sets nullable: false in a custom JSON schema, as in the following scenario, it will be ignored?
> ```
> val customSchemaJson = <...some custom JSON schema...>
> val customSchema = DataType.fromJson(customSchemaJson).asInstanceOf[StructType]
> spark.read.schema(customSchema).json("/path/to/data.json")
> ```

With the response:

>Yes, for now. That's what happens now.

With all these, is quite impossible to directly read a parquet file and write its rows to an already present Iceberg dataset having a required field, even though the schemas are the same.

The main use case is directly **updating an Iceberg dataset from a Parquet file**.

Here is a test I put together to demonstrate the issue: https://gist.github.com/andrei-ionescu/e2d4918264b4acea1599ba2516d2f125.

The **proposal** would be — understanding that Spark won't change it soon — for **Iceberg to loosen up by checking the nullability property of nested fields only**.

**Comment by rdblue** [comment]
> Please note that both have the same schema.

The problem is that these do not have the same schema. If the Parquet schema does not have field IDs, then the IDs are assigned using the fallback logic. The fallback logic matches columns by position, not by name.

If you want to read this file, you need to create a name-to-id schema mapping. Those were added in #338. You'd also need to update the fallback strategy in Parquet to use the schema mapping to assign IDs when one is present, instead of the default position-based approach.

@rdsr, FYI

**Comment by rdblue** [comment]
Sorry, I was wrong about that in the comment above. Since this is validating the write schema, the Parquet schema handling has nothing to do with it. I made an assumption because Parquet was mentioned in the summary. I'll take a closer look at this.

**Comment by andrei-ionescu** [comment]
Thanks @rdblue.

**Comment by rdblue** [comment]
@andrei-ionescu, sorry for the delay, I had fallen behind with reviews.

I agree with your assessment of the problem. Spark is producing a schema that marks all fields nullable, which breaks because Iceberg validation is strict so that errors are caught at job planning time, rather than at runtime.

While you could fix this with a UDF that returns a type is not nullable, that's not a great solution because people need to know to write that UDF and it's a big annoyance.

I think it would be reasonable to have a write option that will relax this constraint. That could be an Spark option (`spark.sql.iceberg.disable-nullability-check`) or could be an option passed to the write in DataFrameWriter (`df.write.option("disable-nullability-check", "true")`).

**Comment by andrei-ionescu** [comment]
Thank you @rdblue, I’ll add the changes soon on the https://github.com/apache/incubator-iceberg/pull/514 PR.

**Comment by rdsr** [comment]
Wouldn't this option allow writing fields which are really optional in the parquet file as **required** fields in the table.  This could fail reads from the said table as a record could have a required field missing.  

Is it an option to instead of reading using parquet source, we register those files as Iceberg table and then read from them?

**Comment by andrei-ionescu** [comment]
@rdsr Can you provide a gist of this in a Spark distributed manner? 

Writing data once more to disk is not a viable solution because it will double the space for storage and/or maybe additional processes to clean up.

**Comment by rdsr** [comment]
@andrei-ionescu I don't think we have to rewrite the data, we could just register the parquet files we want to read with a table. I think `SparkTableUtil` may help us do that but I haven't explored that api

**Comment by andrei-ionescu** [comment]
So... given a parquet file, let me put the steps you are proposing and correct me if I’m wrong:

1. Get schema (load the data which leads to memory consumption)
2. Create new table (need write permissions and space is taken for metadata to be added plus cleanup)
3. Read data using Iceberg data frame reader (once more memory consumption)
4. Write that to the other iceberg dataset with data frame writer

If these are the steps there are the following drawbacks:

- More memory required
- Write access to the source
- Cleanup process to remove the artificially added metadata

In the end I want to add that I already tried something similar but **failed** due to memory consumption. 

```
val schema = ParquetSchemaUtil.convert(icebergSchema)
val dataset = sparkSession.read.schema(schema).parquet(sourcePath)
val datasetWithCorrectSchema = sparkSession.sparkContext.createDataFrame(dataset.rdd, schema)
datasetWithCorrectSchema.write.format(“iceberg”).save(targetPath)
```

**Comment by rdsr** [comment]
The data will not be read. It will only be a metadata operation. We'd have to read Parquet footer to load the metrics only.

**Comment by andrei-ionescu** [comment]
@rdsr Given two different locations of data (`hdfs://host_1/input/data/` and `hdfs://host_2/input/data/`), how would you move the `day=2019-06-01` partition from **host_1** to **host_2** applying some transformations (host_1 data is parquet format, host_2 data is iceberg format)?
