### ISSUE TITLE
[Spark-3] Add PreferredLocations support for ReadTask

### ISSUE THREAD

**Issue by jerryshao** [apache/incubator-iceberg#697]

**Comment by rdblue** [comment]
I'm not sure that we will want to do this. Iceberg doesn't currently support this because it doesn't get locality information before planning splits. Split planning is handled entirely with Iceberg metadata.

We could add locality by looking up the locality of files in a split, or by providing a method that lazily loads locality information. But both of those options will require remote calls to HDFS, so it would be very expensive.

**Comment by jerryshao** [comment]
What we did internally is to trigger RPC calls to get block information. Yes, there's overhead to trigger RPC calls, but I think this is a trade-off between locality and split planning. In object store like S3, locality may not be so important and to get block information has big overhead, but for HDFS, it may not be so big. So I think we may provide a conf to report locality information or not, and turn it off by default.

**Comment by rdblue** [comment]
@jerryshao, are you looking up each file status individually? Is there a bulk API that we can use?

I'm +1 for having a flag to turn it on and off. We can also default based on a white list of locality file systems, like HDFS.

**Comment by jerryshao** [comment]
Currently we're looking up each file status individually, I'm not sure if there's bulk APIs we can use, let me search it.

**Comment by rdblue** [comment]
Merged #721. Thanks @jerryshao!
