### ISSUE TITLE
make org.apache.iceberg. PartitionData public

### ISSUE THREAD

**Issue by sudssf** [apache/incubator-iceberg#764]
PartitionData.java is using default classifier for defining class which makes it inaccessible from any other package.
we need this class to be public so that external code and perform operations such as append to table, add files  etc for partitioned table.

**Comment by rdblue** [comment]
I don't think that this necessarily needs to be public. It's an internal implementation that is not part of the public API. What are you trying to do? Can you pass `StructLike` instead?

**Comment by sudssf** [comment]
Thanks @rdblue  for reply. in one of our ingestion flow, we are writing files directly to iceberg table using java API. when we build location string and datafiles I am not sure how to pass partition information using `StructLike` as its interface.

for now I am using following API when creating data files
` new DataFiles.Builder(table.spec).withPartition(partLike)`

there is helper method which returns PartitionData
```
def getPartitionData(spec: PartitionSpec, par : String) : PartitionData = {
    val partition = new PartitionData(spec.partitionType())
    partition.set(0, par)
    partition
  }
```

can you point me to example where we can use `StructLike` directly?

**Comment by rdsr** [comment]
@sudssf you should be able to implement `StructLike`  e.g
```
 return new StructLike() {
      @Override
      public int size() {
        return // return number of your partition columns
      }

      @Override
      public <T> T get(int pos, Class<T> javaClass) {
        // At this point you should have all partition column values. You may return the one based on `pos`;
      }

      @Override
      public <T> void set(int pos, T value) {
         // maybe just throw?
        throw new UnsupportedOperationException("Set not supported");
      }
    };
```

What's your concern?

**Comment by sudssf** [comment]
@rdsr yes interface can be implemented which code would you prefer implementing `StructLike` or  reusing boilerplate from `PartitionData`?
also partition logic is much cleaner using `PartitionSpec`.

**Comment by rdblue** [comment]
We don't want to open up `PartitionData` because it includes quite a bit that we don't want to make part of our public API. For example, it implements Avro's `IndexedRecord` API that we may not support indefinitely. The guarantee we provide is `StructLike`.

But, you should be able to use [`GenericRecord`](https://github.com/apache/incubator-iceberg/blob/master/data/src/main/java/org/apache/iceberg/data/GenericRecord.java) with `PartitionSpec.partitionType()` to get a `StructLike` that works for you without implementing that interface directly. Of course, you're welcome to implement that interface if you'd like more control over the implementation.

**Comment by sudssf** [comment]
thanks @rdblue  I test using `GenericRecord `
