### ISSUE TITLE
Consider upgrading built-in Hive version to 2.3.x

### ISSUE THREAD

**Issue by jerryshao** [apache/incubator-iceberg#832]
I would like to bring out the discussion about upgrading the built-in Hive support version from 1.2.1 to 2.3.x. The reason for this upgrading is:

1. The community is working on Hive Iceberg support, and there's some potential version problems (https://github.com/apache/incubator-iceberg/issues/170#issuecomment-594122562).
2. The version 1.2.1 is quite old, most of the frameworks now move on to 2.3.x, like Spark.

Please share your comments.

CC @rdblue @rdsr .

**Comment by rdblue** [comment]
The reason for using 1.2.1 is that's the version Spark uses. When we update to Spark that depends on something other than 1.2.1-spark2, I think we all agree we should update.

I also thought that it was safer to depend on 1.2.1, so that we don't use any new APIs that are incompatible with that version. But it should be safe to update to 2.3.x as long as we test the spark-runtime Jar with 2.4.x versions of Spark where 1.2.1-spark2 is the provided version.

Since the Hive catalog is fairly stable at this point, I think it probably makes sense to update to 2.3.x to enable Hive/Iceberg support.

**Comment by jerryshao** [comment]
I think it should be worked when upgrading to Hive 2.3.x, I will take a try on this.
