### ISSUE TITLE
We should publish a shaded version of problematic dependencies to use in Iceberg

### ISSUE THREAD

**Issue by rdsr** [apache/incubator-iceberg#934]
As discussed in our meetup, we should have a shaded version of guava. There are two ways of doing this 
- Add a Gradle module, which will be an empty module with only the problematic dependencies- guava, jackson etc. This will work fine for Gradle build, but has 2 main downsides
   - Intellij does not understand it well. In my experience there will be class-path conflicts when working from within Intellij as it will fail to import the shaded jar well.
   - Another issue is that we will always have to rebuild the shaded module during build, which would increase our interactive development time and can hinder in development.
- Another option is publish the problematic shaded artifact [iceberg-problematic-deps e.g]  first to some public repository. It will fix both the above problems. Intellij will work and will also save us from rebuilding  the shaded module every time during the build. Though I'm not sure where will we house this repo

Any thoughts on which one people prefer?

**Comment by aokolnychyi** [comment]
@rdsr, I've missed the sync. Is this needed for people who depend on `core`?

**Comment by rdsr** [comment]
Hi @aokolnychyi , @massdosage and team are working on a HiveStorageHandler which would go in `iceberg-hive` module. I think they have faced class-path issues relying on iceberg core modules together with hive artifacts in `iceberg-hive`

I too faced an issue with Guava where I was unable to run Mini HDFS to test iceberg-mr because of guava conflicts.

**Comment by massdosage** [comment]
Yes, `iceberg-hive` depends on `iceberg-core`, `iceberg-api`, `iceberg-common` and `iceberg-mr` so all of these jar files will need to go on Hive's classpath when you use any of the classes inside iceberg-hive. Due to Guava version conflicts with the version of Guava used by Hive all usages of Guava inside Iceberg's classes need to be shaded and reolcated otherwise there are runtime version conflicts which prevent being able to integrate Iceberg and Hive. I would imagine there would be similar issues with anyone using any Iceberg modules via an API and also having their own version of Guava so would recommend applying this across the whole project if possible.

**Comment by jerryshao** [comment]
Apache Ratis uses another repo to manage all the shaded artifacts and publish again to the maven central repo. That's the second way mentioned by @rdsr https://github.com/apache/incubator-ratis-thirdparty/

**Comment by massdosage** [comment]
Can we close this now since https://github.com/apache/incubator-iceberg/pull/935 has been merged? We can always open more specific tickets for other issues we find going forward but I think the main objective has been achieved for Guava.
